---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator-mgmt
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://pkgs.tailscale.com/helmcharts
      chart: tailscale-operator
      targetRevision: 1.82.0
      helm:
        valuesFiles:
          - $values/bootstrap/tailscale-operator/mgmt/values-mgmt.yaml
    - repoURL: https://github.com/combrink/zoo.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
