---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-homelab
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: secrets
  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    chart: sealed-secrets
    targetRevision: 2.18.4
    helm:
      releaseName: sealed-secrets
  destination:
    server: https://k3d-homelab-serverlb:6443
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
