---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-secrets-homelab
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: secrets
  source:
    repoURL: https://github.com/combrink/zoo.git
    targetRevision: HEAD
    path: bootstrap/tailscale-operator/homelab
  destination:
    server: https://k3d-homelab-serverlb:6443
    namespace: tailscale
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
